### ISSUE TITLE
KeyError: 'fc6/b is not a file in the archive'

### ISSUE THREAD

**Issue by guyuchao** [alokwhitewolf/Guided-Attention-Inference-Network#3]
After training classifer, it generates snapshot. When i use this snapshot to train gain, this error occurs. Maybe fc6/b is bias of conv layer, which is not in classifier model. In classifier, it is fully connected layer named fc6_cl. 
I am new to chainer, how to load snapshot to Gain model?

**Comment by alokwhitewolf** [comment]
Hey. I have corrected some typos that were there in some earlier commits. Although I am unsure about your error, as you haven't put your error message

I have ran the latest commits in my machine and it works fine. Please put your error message.

**Comment by alokwhitewolf** [comment]
I am unable to replicate your issue. The code as it is in this repo right now, works fine for me in my machine. Try running with the latest commit as there were some typos in the prev commits. 

I am closing this issue as of now. Reopen if the problem persists. Thanks
