### ISSUE TITLE
The implement of attention loss

### ISSUE THREAD

**Issue by oyxhust** [alokwhitewolf/Guided-Attention-Inference-Network#5]
Thanks for this great implement. I go through your codes, and find that this repo has implemented the classification loss and attention mining loss in the paper. Do you have the plan to add the attention loss (directly compare the l2 distance of the attention map and pixel-wise mask) in the paper? Meanwhile, I notice that you add the segmentation loss in this repo. This segmentation loss is helpful for generating an accurate attention map?

**Comment by alokwhitewolf** [comment]
Hello. Thanks for going through the repo. Originally, I didn't have the need for the extra supervision part, so I thought better to not implement it. Right now, although I have no plans as such to add the GAIN_ext part of the paper as I haven't been able to make out time to work on this project, I might take out some time to work on adding the remaining section. Although, you are free to send a PR for that section as well.

Yes, that was my experience. Pure GAIN loss lead to bad results in my implementation.

**Comment by oyxhust** [comment]
Thanks for your quick reply. Another question is that I am not very clear with the "Quantitative Results" part in the ReadMe. Could you help to explain that the mean of  "Accuracy | Accuracy Class | Mean IU | FWAVACC | Model File"? 

I think the original paper is designed to improve the performance of the attention map, and this repo is used to improve the segmentation performance. So I am wondering that it can help for the segmentation or not. But I do not totally understand the table in the "Quantitative Results" part in the ReadMe.

**Comment by alokwhitewolf** [comment]
My takeaway was that the paper tries to explicitly improve the attention map generated in order to improve semantic segmentation performance. This could be apparent from the fact that in the paper, they have compared semantic segmentation performances with other methods.

Those are the metrics to evaluate segmentation. I was trying to see if there are any changes in the metrics from the original fcn model after doing GAIN training,

**Comment by oyxhust** [comment]
Okay! Hope it can work! Thanks a lot for your reply.
