### ISSUE TITLE
why assert image.shape[0] == 1, "Batchsize of only 1 is allowed for now" ??

### ISSUE THREAD

**Issue by nashory** [alokwhitewolf/Guided-Attention-Inference-Network#6]
Thanks for nice implementation!
I found you commented 'assert image.shape[0] == 1, "Batchsize of only 1 is allowed for now"' in the code, 
and wonder why you limited the batch size to 1.   
Is there any operation that force you to limit batchsize = 1 ?
Thanks!

**Comment by alokwhitewolf** [comment]
Sorry for the late reply. 

I had asserted because PascalVOC dataset had images of variable sizes. I rather thought of limiting the batch size to one in order to circumvent that. You could very well resize the images and the target labels and try with batch != 1
