### ISSUE TITLE
Trying to understand why xp.random.choice was used in set_init_grad function when the labels are available

### ISSUE THREAD

**Issue by hawkeyedesi** [alokwhitewolf/Guided-Attention-Inference-Network#7]
Thanks for your code. 
I had a question of the set_init_grad code reference here: 
https://github.com/alokwhitewolf/Guided-Attention-Inference-Network/blob/cd1cb0ac021078ed42fe3c1456040c00622e79d7/GAIN.py#L54-L63

On line 61, you use `xp.random.choice(label,1)`. Can you explain why are you using random choice when you know the ground truth label index? I did not see that in the original paper and was curious to know if it improved your accuracy or performance. @alokwhitewolf

**Comment by Giuseppe5** [comment]
Hello,
Thanks for the code. I went through it and I asked myself this exact same question. Would be possible to have a comment on this? Thanks.
