### ISSUE TITLE
Do I need to install any deep-learning libraries?

### ISSUE THREAD

**Issue by MubarkLa** [alokwhitewolf/Guided-Attention-Inference-Network#8]
Thanks a lot for your great work.
I have read your paper and now try to reproduce your work.
For this purpose, do I need to install any deep-learning libraries, such as pytorch or tensorflow?
Thanks a lot.

**Comment by alokwhitewolf** [comment]
Yes, you need to install Chainer library. I have added the details in README

Also, the GAIN paper is NOT my work.
